name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.10]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install qutip-symbolic
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Test with pytest
      run: |
        pytest tests --strict-config --strict-markers --verbosity=1
